git clone git@github.com:p15/phosphorus-api-ruby-client.git
git clone git@github.com:p15/phosphorus-atomic.git
git clone git@github.com:p15/phosphorus-engine.git
git clone git@github.com:p15/phosphorus-mgmt.git
git clone git@github.com:p15/phosphorus-one.git
git clone git@github.com:p15/phosphorus-practice.git
git clone git@github.com:p15/pipeline-scripts.git
git clone git@github.com:p15/recombine-api.git
git clone git@github.com:p15/recombine-mgmt.git
git clone git@github.com:p15/recombine-migrations.git
git clone git@github.com:p15/recombine-rails-suite.git
git clone git@github.com:p15/workflow-utils.git
